<template>
  <div>
    <a
      href="https://www.google.com"
      target="_blank"
      ><img
        src="https://cache.addthiscdn.com/icons/v3/thumbs/32x32/email.png"
        border="0"
        alt="Email"
    /></a>
    <a
      href="https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=https%3A%2F%2Fwww.addthis.com%2F&pubid=ra-42fed1e187bae420&title=AddThis%20%7C%20Home&ct=1"
      target="_blank"
      ><img
        src="https://cache.addthiscdn.com/icons/v3/thumbs/32x32/facebook.png"
        border="0"
        alt="Facebook"
    /></a>
    <a
      href="https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=https%3A%2F%2Fwww.addthis.com%2F&pubid=ra-42fed1e187bae420&title=AddThis%20%7C%20Home&ct=1"
      target="_blank"
      ><img
        src="https://cache.addthiscdn.com/icons/v3/thumbs/32x32/twitter.png"
        border="0"
        alt="Twitter"
    /></a>
    <a
      href="https://api.addthis.com/oexchange/0.8/forward/whatsapp/offer?url=https%3A%2F%2Fwww.addthis.com%2F&pubid=ra-42fed1e187bae420&title=AddThis%20%7C%20Home&ct=1"
      target="_blank"
      ><img
        src="https://cache.addthiscdn.com/icons/v3/thumbs/32x32/whatsapp.png"
        border="0"
        alt="WhatsApp"
    /></a>
    <a
      href="https://api.addthis.com/oexchange/0.8/forward/gmail/offer?url=https%3A%2F%2Fwww.addthis.com%2F&pubid=ra-42fed1e187bae420&title=AddThis%20%7C%20Home&ct=1"
      target="_blank"
      ><img
        src="https://cache.addthiscdn.com/icons/v3/thumbs/32x32/gmail.png"
        border="0"
        alt="Gmail"
    /></a>
  </div>
</template>

<script>
export default {};
</script>

<style>
</style>